config_type: "virus_host_prediction_external"

# Input Settings:
  ## initialize base input folder name
  ## provide path to dataset folder
input_settings:
  # Base input directory
  input_dir: "input/data/coronaviridae/20250616"

  # Name of file(s) in subdirectory to be read and processed.
  # Example: file_names: ["file_1.csv", "file_2.csv", "file_3.csv"]
  # file_names: [ "uniref90_final_msl1114.csv" ]
  file_names: [ "final_filtered_df.csv" ]
  # seeds to split the files into training and testing
  # if provided, the number of seeds must match the number of iterations configured in classification_settings (n_iterations)
  split_seeds: [ 12612648, 31062180, 48918293, 55631155, 79221635 ]

sequence_settings:
    batch_size: 16 #changed this to 16
    id_col: "uniref50_id"
    sequence_col: "seq"
    truncate: False
    max_sequence_length: 2582 #changed this from 2048 to 2582
    split_sequence: False
    feature_type: "token"  # supported values 'kmer', 'cgr', 'token'

fine_tune_settings:
  experiment: "virus_host_prediction_external"
  n_iterations: 5
  split_input: True
  train_proportion: 0.8
  classification_type: "multi"
  save_model: True

  training_settings:
    n_epochs: 50
    max_lr: 3e-4
    pct_start: 0.10
    div_factor: 25.0
    final_div_factor: 10000.0

  label_settings:
    label_col: "virus_host_tax_id"
    exclude_labels: [ "nan" ]
    label_groupings:
      "Human": [ 9606 ]
      "Chicken": [ 9031 ]
      "Cat": [ 9685 ]
      "Pig": [ 9823 ]
      "Gray wolf": [ 9612 ]
      "European rabbit": [ 9986 ]

  task_settings:
    - id: "prostt5_fnn_2l_d1024_lr3e-4"
      name: "ProstT5"
      active: False
      mode: "train" # supported values: train, test
      fine_tuned_model_path: ""
      pre_trained_model_link: "Rostlab/ProstT5"
      hugging_face_cache_dir: "output/cache_dir"
      loss: "FocalLoss"
      n_mlp_layers: 2
      n_classes: 6
      input_dim: 1024 # input embedding dimension
      hidden_dim: 1024
      data_parallel: False

    - id: "prot_t5_xl_uniref50_fnn_2l_d1024_lr3e-4"
      name: "ProtT5"
      active: True
      mode: "train" # supported values: train, test
      fine_tuned_model_path: ""
      pre_trained_model_link: "Rostlab/prot_t5_xl_uniref50"
      hugging_face_cache_dir: "output/cache_dir"
      loss: "FocalLoss"
      n_mlp_layers: 2
      n_classes: 6
      input_dim: 1024 # input embedding dimension
      hidden_dim: 1024
      data_parallel: False

    - id: "esm2_t12_35M_UR50D_bn_fnn_2l_d1024_lr1e-4"
      name: "ESM2"
      active: False
      mode: "train" # supported values: train, test
      fine_tuned_model_path: ""
      fine_tuned_model_name: "esm2_t12_35M_UR50D" # "esm2_t36_3B_UR50D" # "esm2_t48_15B_UR50D" # "esm2_t33_650M_UR50D"
      repr_layer: 12 # 36 # 48 # 33
      input_dim: 480 # 2560 # 5120 # 1280 # input embedding dimension
      loss: "FocalLoss"
      n_mlp_layers: 2
      n_classes: 6
      hidden_dim: 1024
      data_parallel: False

    - id: "esm3_bn_fnn_2l_d1024_lr1e-4"
      name: "ESM3"
      active: False
      mode: "train" # supported values: train, test
      fine_tuned_model_name: "esm3-open"
      input_dim: 1536
      loss: "FocalLoss"
      n_mlp_layers: 2
      n_classes: 6
      hidden_dim: 1024
      data_parallel: False

output_settings:
  output_dir: "output"
  results_dir: "raw"
  sub_dir: "uniref50_coronaviridae/uniref50_corona_top_hosts"
  prefix: "uniref50coronaviridae" # default: none; default file name = kmer_k<k>_lr_c<c>_<label>_<type>_tr<train_proportion>_n<n_iterations>_<output_prefix>_output.csv
