config_type: "virus_host_prediction_baseline_deep_learning"

# Input Settings:
  ## initialize base input folder name
  ## provide path to dataset folder
input_settings:
  # Base input directory
  input_dir: "input/data/bvbrc"

  # Name of file(s) in subdirectory to be read and processed.
  # Example: file_names: ["file_1.csv", "file_2.csv", "file_3.csv"]
  file_names: [ "BVBRC_reference_genome_20260429_proteome_proteins_host_prevalence_gte_onepercent.csv" ]
  # seeds to split the files into training and testing
  # if provided, the number of seeds must match the number of iterations configured in classification_settings (n_iterations)
  split_seeds: [ 12612648, 31062180, 48918293, 55631155, 79221635 ]

sequence_settings:
    batch_size: 16
    id_col: "protein_id_name"
    virus_col: "virus_genus_tax_name"
    sequence_col: "sequence"
    truncate: False
    split_sequence: False
    feature_type: "token"  # supported values 'kmer', 'cgr', 'token'

classification_settings:
  experiment: "virus_host_prediction_baseline_deep_learning"
  n_iterations: 5
  split_input: True
  split_input_col: "virus_genus_tax_name"
  train_proportion: 0.8
  classification_type: "multi"
  save_model: True

  training_settings:
    n_epochs: 50
    max_lr: 1e-3
    pct_start: 0.10
    div_factor: 25.0
    final_div_factor: 10000.0

  label_settings:
    label_col: "virus_host_species_tax_id"
    exclude_labels: [ "nan"]
    label_groupings:
      "Human": [ 9606 ]
      "Chicken": [ 9031 ]
      "Pig": [ 9823 ]
      "Domestic cattle": [ 9913 ]
      "Norway rat": [ 10116 ]
      "Horse": [ 9796 ]
      "Wolf": [ 9612 ]
      "Boa": [ 8574 ]

  models:
    - id: "fnn-l_10-d_1024-lr1e-3"
      name: "FNN"
      active: False
      mode: "train" # supported values: train, test
      loss: "FocalLoss"
      n_mlp_layers: 10
      n_classes: 5
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      manual_seed:  # whole number
      data_parallel: False

    - id: "cnn-l_4-d_1024-k3s1-lr1e-3"
      name: "CNN"
      active: True
      mode: "train" # supported values: train, test
      loss: "FocalLoss"
      n_layers: 4
      n_mlp_layers: 2
      n_classes: 5
      input_dim: 1024 # input embedding dimension
      hidden_dim: 1024
      kernel_size: 3
      stride: 1
      manual_seed:  # whole numbers
      data_parallel: False

    - id: "rnn-l_6-d_1024-lr1e-5"
      name: "RNN"
      active: False
      mode: "train" # supported values: train, test
      loss: "FocalLoss"
      n_layers: 6 # number of rnn layers
      n_mlp_layers: 2
      n_classes: 5
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      manual_seed:  # whole numbers
      data_parallel: False

    - id: "lstm-l_2-d_1024-lr1e-3"
      name: "LSTM"
      active: False
      mode: "train" # supported values: train, test
      loss: "FocalLoss"
      n_layers: 2
      n_mlp_layers: 2
      n_classes: 5
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      manual_seed:  # whole numbers
      data_parallel: False

    - id: "transformer-l_6-h_8-d_1024-msl2048-lr1e-4"
      name: "Transformer_Encoder"
      active: False
      mode: "train" # supported values: train, test
      loss: "FocalLoss"
      with_convolution: False
      max_seq_len: 3036 # this is needed only for the positional encoding initialization
      n_heads: 8
      n_layers: 6
      n_mlp_layers: 2
      n_classes: 5
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      manual_seed:  # whole numbers
      data_parallel: False

output_settings:
  output_dir: "output"
  results_dir: "raw"
  sub_dir: "uniref90_embl_vertebrates_non_idv_t0.01_c5_seq_len_in_99.9percentile/20240729/host_multi"
  prefix: "test" # default: none; default file name = kmer_k<k>_lr_c<c>_<label>_<type>_tr<train_proportion>_n<n_iterations>_<output_prefix>_output.csv
